### ISSUE TITLE
PgDb.connect() dies when it sees a schema name it doesn't need

### ISSUE THREAD

**Issue by fburleigh** [holdfenytolvaj/pogi#14]
My app has begin to [throw an exception in pgDb.js](https://github.com/holdfenytolvaj/pogi/blob/c9183b68e5e87d37125a7e0177bea1085bf74345/lib/pgDb.js#L187) during connect() despite no changes to code, process, or data. I believe the addition of a new schema to the EDB variant of the PostgresSQL 9.6 database has surfaced this behavior. The new schema is not related to the app; the role for the app's schema has no access to the new schema. My guess is that the [query that finds "special field types"](https://github.com/holdfenytolvaj/pogi/blob/c9183b68e5e87d37125a7e0177bea1085bf74345/lib/pgDb.js#L32) unnecessarily reveals schema names it does not need.

I do not know whether to consider this a design issue in Pogi, or a problem in the way I use it. The first few lines in my app are:

```typescript
(async () => {
    const db = await PgDb.connect({connectionString: "postgres://app_media@<host>:<port>/<db>"});
    const quotedFaculty = await db.query(assets.selectAppearingFacultyLastYear);
    ...
})();
```

My intellectual problem is that this behavior would affect any app using a database with more than one user-type schema. So, I look forward to another analysis -- because I don't trust mine. ;-)

**Comment by holdfenytolvaj** [comment]
I can confirm this is design issue.
(even so psql should not leak info about schemas that the user has no access to)
I will change the exception to log, as it was there only for sanity check anyway.

**Comment by holdfenytolvaj** [comment]
Published a new version

**Comment by fburleigh** [comment]
Thank you for this work. My app's function is restored.
