### ISSUE TITLE
PgDb.js depends on module extsprintf, but Pogi does not install it

### ISSUE THREAD

**Issue by fburleigh** [holdfenytolvaj/pogi#15]
A recent update to PgDb.js that fixes #14 adds a requirement for module extsprintf, but Pogi's install does not install it. That makes Pogi except my app. I suspect this is cruft from a debug session.

Additionally, PgDb.js emits a query's text (prefaced with 'GGG'). I suspect that, too, is not intended, outside the context of a logger being enabled.

**Comment by holdfenytolvaj** [comment]
The log is a shame, the first was missing probably as I only used yarn.
In any case it is not an important dependency, i've removed it instead.

Thanks a lot!

**Comment by fburleigh** [comment]
And thank _you_ a lot!
