### ISSUE TITLE
support for running initialization query

### ISSUE THREAD

**Issue by tyriis** [holdfenytolvaj/pogi#17]
Hello,

first: I really like your work. This is a really nice library without all the orm magic and abstraction layers.

problem: when I try to execute an initialization query (table create script) on an empty database, I got an error because the database is already queried during connect() but is empty.

Is there any way to work around this connection startup queries?

best regards

```
debug: [QUERY] SELECT current_schemas(false)
(node:23208) UnhandledPromiseRejectionWarning: Error: No readable schema found
```

**Comment by holdfenytolvaj** [comment]
Very good point, yes we should certainly support it.

**Comment by holdfenytolvaj** [comment]
So we threw that error, so changed that in the new version to just a warning.
