### ISSUE TITLE
Document the `close` method

### ISSUE THREAD

**Issue by ab-pm** [holdfenytolvaj/pogi#19]
From studying the code, I just found out that `PgDb` has a `close()` method, which is indispensable in integration tests.

Please document it on https://pogi.readthedocs.io/en/latest/API/PgDb/.

**Comment by holdfenytolvaj** [comment]
Interesting enough it was in the md file, but the hook on github got lost somehow and did not trigger the readthedocs. Thanks for catching this.

**Comment by gombosg** [comment]
Yep that was in pull #16 :wink:
