### ISSUE TITLE
underscore to camelCase convertion

### ISSUE THREAD

**Issue by patte** [holdfenytolvaj/pogi#2]
hi! awesome library, thanks!
Is there a possiblity to automatically camelize object keys? Or an easy way to patch find, to do it myself?

**Comment by holdfenytolvaj** [comment]
Hi!

What do you mean exactly?
if the column name is camelized in psql eg.` "firstName"` the `users.findAll()` (and the others) will return
`[{firstName:'Mark'},{firstName:'Bob'}]`. Just have to take care of adding the double quotes around the column names in all manual queries for psql.
 
e.g.: 
`CREATE TABLE IF NOT EXISTS "users" (
	"id" SERIAL PRIMARY KEY,
	"firstName" varchar 
);
`

**Comment by patte** [comment]
Thanks for the fast response.
My database is snake_case. Right now I'm using [humps](https://github.com/domchristie/humps) after every pgdb query to convert the object keys to camelCase, because the result gets published by apollo graphql. I was wondering if you could support that or if I can easily monkey patch the feature.

**Comment by holdfenytolvaj** [comment]
as for monkey patch it's easy to add to:
pgUtils->postProcessResult
I will add a "hook" to support it.. but be gentle with the deadline :)
Lets keep this open.

**Comment by patte** [comment]
A postProcess hook would be amazing!
No hurry, awesome, thanks!

**Comment by patte** [comment]
by the way, small question. how are you personally handling this? Do you use camelCase for column names. Then what do you do with table names? postgres converts them to lowercase if they are not quoted. Do you go mixed, fully snake_case or fully camelCase? Just wondering.

**Comment by holdfenytolvaj** [comment]
we are using camelCase everywhere (table+column names), pogi handles it well, so from js no extra care is needed.  It's only a bit bothersome for manual queries, but I already got used to that, so wont even notice.

**Comment by holdfenytolvaj** [comment]
Hi!
I've added the 

`pgdb.setPostProcessResult(f:(res: any[], fields: ResultFieldType[], logger:PgDbLogger)=>void) {this.postProcessResult = f;}
`
where 


```
    interface ResultFieldType {
        name: string,
        tableID: number,
        columnID: number,
        dataTypeID: number,
        dataTypeSize: number,
        dataTypeModifier: number,
        format: string
    }
    interface PgDbLogger {
       log: Function;
       error: Function;
    }

```

function, but only tested a bit. So please make sure :D it works as intended.

```
    it("Testing postprocess function",  w(async() => {
        await table.insert({name: 'A'});

        pgdb.setPostProcessResult((res, fields, logger)=> {
            res[0].name='B';
        });
        let res = await pgdb.query(`select * from ${table}`);
        expect(res[0].name=='B').toBeTruthy();
        res = await table.findAll();
        expect(res[0].name=='B').toBeTruthy();
        pgdb.setPostProcessResult(null);
    }));
```

**Comment by holdfenytolvaj** [comment]
Close as being inactive.
