### ISSUE TITLE
Pogi with cockroachDB

### ISSUE THREAD

**Issue by ansarizafar** [holdfenytolvaj/pogi#3]
Is it possible to use Pgi with cockroachDB. I am getting this error pg_trigger" does not exist.

**Comment by holdfenytolvaj** [comment]
I'm afraid no, as we use some postgreSQL specific feature (e.g. looking up array and jsonb column types to handle the automatic conversion). It might be possible that just with deletion it could make it work, but in any case it suits better for a new project to avoid confusion about psql specific features.
