### ISSUE TITLE
ES2015 compiled JS files

### ISSUE THREAD

**Issue by gergely-ujvari** [holdfenytolvaj/pogi#5]
Hello,

I'm trying to use your great library together with Meteor, but currently Meteor has an issue that it cannot use ES2015 compiled js files from NPM. And I see that you compile your ts files into ES2015 js files. My question is, can you consider maybe compiling your package to ES5 compatible js files, or maybe do you know a way to use your package together with Meteor? I have seen hints in your blog post that you were/are using also Meteor.

Thank you

**Comment by garaboncias** [comment]
Hi!
We do not use Meteor, but i think "babel-register" maybe solve your problem. If you only have problem with our repo, please send a pull request for suitable build parameters.

**Comment by holdfenytolvaj** [comment]
Close as being inactive
