### ISSUE TITLE
Problem perhaps related to limited access rights when reading metadata

### ISSUE THREAD

**Issue by jarlestabell** [holdfenytolvaj/pogi#6]
Hi,
When using pogi with a postgres user which has rather limited access rights, I get a problem in pgDb.ts, in the initFieldTypes() function.
The error I get is "Cannot read property 'fieldTypes' of undefined".

If I change this:
```javascript
...
for (let r of specialTypeFields.rows) {
            this.schemas[r.schema_name][r.table_name].fieldTypes[r.column_name] =
                ([3802, 114].indexOf(r.typid) > -1) ? FieldType.JSON :
                    ([3614].indexOf(r.typid) > -1) ? FieldType.TSVECTOR :
                    ([1082, 1083, 1114, 1184, 1266].indexOf(r.typid) > -1) ? FieldType.TIME :
                        FieldType.ARRAY;
...
```
into something like:

```javascript
...
for (let r of specialTypeFields.rows) {
   if(this.schemas[r.schema_name][r.table_name]) { 
            this.schemas[r.schema_name][r.table_name].fieldTypes[r.column_name] =
                ([3802, 114].indexOf(r.typid) > -1) ? FieldType.JSON :
                    ([3614].indexOf(r.typid) > -1) ? FieldType.TSVECTOR :
                    ([1082, 1083, 1114, 1184, 1266].indexOf(r.typid) > -1) ? FieldType.TIME :
                        FieldType.ARRAY;
   }
...

```
ie inserting an if test to check if we actually have the table metadata, pogi seems to work ok also in my case with limited postgres privileges.

**Comment by holdfenytolvaj** [comment]
Thanks for the report!

And sorry for the delay, in the meantime I've joined to a big co, and wasn't sure whether I can work on this project. But apparently yes. Just added the fix and published it!
Thanks again!
