### ISSUE TITLE
transactionBegin returns PgDb instance with empty tables property.

### ISSUE THREAD

**Issue by RayzRazko** [holdfenytolvaj/pogi#7]
Hello,

First I wanted to thank you for that amazing library. 
One thing that I noticed, which seems not to be documented, is that transactionBegin returns PgDb instance which has  empty object in tables property which is confusing.

**Comment by RayzRazko** [comment]
```
const pgDB = await PgDb.connect(config);
const dPgDb = await pgDB.transactionBegin();

console.log(Object.keys(pgDB.tables));
console.log(Object.keys(dPgDb.tables));
```

this will produce next output:

```
[ 
 //list of tables
]
[]
```

**Comment by holdfenytolvaj** [comment]
It was indeed a bug, added a test for it. Thanks

**Comment by RayzRazko** [comment]
Thank you!
