### ISSUE TITLE
Compile error when importing PgDb to typescript file (+ question about 'await')

### ISSUE THREAD

**Issue by tylerpalmerdev** [holdfenytolvaj/pogi#8]
Hi There! I really love Pogi, it seems to be the best all around tool.

But, I'm trying to import the PgDb class into a TS file to create a connection:

```
import { PgDb } from 'pogi';

// set up & connect to postgres db
const dbConfig = {
  host: process.env.DB_URL,
  port: process.env.DB_PORT,
  database: process.env.DB_NAME,
  user: process.env.DB_USER,
  password: process.env.DB_PW,
  max: 10,
  idleTimeoutMillis: 10000,
  poolSize: 10
};

export let connect = async () => {
    return await PgDb.connect(dbConfig);
}
```

And am receiving the follow compilation error:

```
Node] /Users/Tyler/Projects/news-api/node_modules/pogi/lib/pgDb.js:69
[Node]     constructor(pgdb = {}) {
[Node]                      ^
[Node] 
[Node] SyntaxError: Unexpected token =
```
Am I not able to import the PgDb class into a typescript file? I'm currently running node v5.6.0 & npm v5.0.3, if that helps.

Side question: I see a lot of your examples use the `await` keyword outside of an async function. Is that intentional? Usually (at least with TS), that keyword needs to be used inside of an async function.

Thanks for the help!

**Comment by garaboncias** [comment]
Hi therealTP!
Pogi has compiled to node v6 which is the current LTS. If you want to run on node v5 you should use --harmony flag. It should works.
You are right about `await` keyword. we will update the doc.

**Comment by tylerpalmerdev** [comment]
Thanks for the quick reply! I upgraded to node v6 and the issue is fixed. Cheers.

**Comment by holdfenytolvaj** [comment]
Thanks for the note, added the async to doc for the first example. If anywhere you think the doc could be better let me know!
